### ISSUE TITLE
Documentation on `islice_extended` function signature is incorrect

### ISSUE THREAD

**Issue by dsfulf** [more-itertools/more-itertools#426]
Minor issue, but the function signature doesn't list the `iterable` as an argument.

https://more-itertools.readthedocs.io/en/stable/api.html#more_itertools.islice_extended

**Comment by bbayles** [comment]
Would you be up for submitting a PR to correct it?

**Comment by dsfulf** [comment]
I'd be happy to, but it looks more like the docs need to be rebuilt than any code needs to be changed. The signature here [here](https://more-itertools.readthedocs.io/en/stable/_modules/more_itertools/more.html#islice_extended) looks fine.

**Comment by bbayles** [comment]
It should be a matter of editing [this file](https://github.com/more-itertools/more-itertools/blame/master/docs/api.rst#L158). The automatic signature isn't used here, since the function itself looks for a variable list of positional arguments.

If you make a PR with that change, I'll merge it, and ReadTheDocs will generate a new version reflecting the changes.

**Comment by bbayles** [comment]
Thanks!
