### ISSUE TITLE
Consider embedding itertools for developer convenience

### ISSUE THREAD

**Issue by Skeen** [more-itertools/more-itertools#681]
### Description
I find that I often have to lookup whether a certain function is contained within `itertools` or `more_itertools`.

A potential solution to this challenge is to embed `itertools` within `more_itertools`.

This pattern is already utilized by some python libraries, such as [FastAPI](https://github.com/tiangolo/fastapi), which embeds and exposes a lot of the underlying [Starlette](https://github.com/encode/starlette) library as-is. For instance the `status` object:

> FastAPI provides `starlette.status` as `fastapi.status` just as a convenience for you, the developer.
> But it comes directly from Starlette.

### Examples
```python
from itertools import count
from more_itertools import count as mcount

assert count == mcount
```

**Comment by Skeen** [comment]
I imagine this could be implemented by a single line, namely by adding:
```python
from itertools import *  # noqa
```
to `__init__.py` within the `more_itertools` folder.

**Comment by Skeen** [comment]
An alternative approach for implementing this would be wrapping all the functions, to ensure that documentation would be in line with the rest of `more_itertools`.

Doing this would also ensure that all itertools, `more_itertools` and `itertools ` alike would have consitent documentation in one place and in one style.

**Comment by bbayles** [comment]
> I find that I often have to lookup whether a certain function is contained within itertools or more_itertools.

I am the same here, but this approach feels impure to me...

In some cases, functions that were in `more_itertools` have wound up in `itertools` - `pairwise` comes to mind. I've generally deprecated them when this happens, but would you want me to stop doing this in the future?

Comments from others welcome. @rhettinger, in particular, your opinion would be decisive for me.

**Comment by lonnen** [comment]
I haven't had an issue with specific functions moving upstream between versions, but on any given day I couldn't tell you whether `chain` is in `itertools` or `more_itertools` and also have to look it up. In an editor with all my plugins and linters it's a pretty minor inconvenience, though.

I have an intuition that re-exporting part of the standard library is inviting some unexpected hassles between versions of python but I haven't been able to foresee any specific problem. It would certainly be a small ergonomic improvement just to have it in the namespace -- getting the documentation lined up seems like it might pose problems with the differences between the standard lib and historic versions of this library. Maybe it's low churn enough that it's moot.

I do find the ergonomic pain of not knowing which itertools are where a bigger deal in notebooks, REPLs, and iterative development environments. For those I made [oops-all-itertools](https://pypi.org/project/oops-all-itertools/) as a convenience, and will deprecate it if this issue is resolved by re-exporting `itertools`, but at this point I'm not planning on expanding it further with proper documentation or anything.

**Comment by rhettinger** [comment]
> Comments from others welcome. @rhettinger, in particular, your opinion would be decisive for me.

I would leave the two separate.  They are different worlds with distinct ownership, distinct rates of evolution, distinct implementations (C vs pure python), distinct sources of type annotations (typeshed vs self-contained), distinct locations for documentation, and distinct `__module__` attributes.
