### ISSUE TITLE
Itertool proposal: `starfilter` anolog to `starmap`

### ISSUE THREAD

**Issue by DamianB-BitFlipper** [more-itertools/more-itertools#682]
### Description
I have found myself using `starmap` more and more often whenever it makes sense. It mainly makes the code cleaner where if I am iterating over a list of tuples, the lambda function can simply have the values of the inner elements directly rather than relying on some cryptic indexing to get the values I desire. It makes the code easier to write and less error prone.

Well, recently I found myself looking for a `starfilter`, the analog to `starmap` but for filter. I did not find it anywhere. I want to open this issue with the intention of discussing introducing this function to `more-itertools`. I would be more than happy to write the PR for this.

### References
Real problem: I was iterating over a class that implements a grid -- imagine a 2D array. This is a custom class I wrote for a different problem would return an iterable that yields a tuple, the coordinate location and value there: `(coord, pixel)`. The coordinate is in turn a `dataclass` with a `row` and `column` value, but that's not important.

So I wished to filter this iterable over the pixel value, which resulted in this mildly ugly code: `filter(lambda val: val[1] is not None, grid)`.

### Examples
More cleanly, the code could look like: `starfilter(lambda _, pixel: pixel is not None, grid)`

**Comment by Skeen** [comment]
Assuming this idea gets approved, and this PR #680 gets merged, it might make sense to expand the scope here to include a `starstarfilter` / `doublestarfilter`:
```python
>>> iterable = [{'a': 1, 'b': 2}, {'a': None, 'b': 4}, {'a': 5, 'b': 6}]
>>> starstarfilter(lambda a, b: a is not None, iterable)
[{'a': 1, 'b': 2}, {"a": 5, 'b': 6}]
```
Something along the lines of:
```python
def starstarfilter(func, iterable):
    for item in iterable:
        if func(**item):
            yield item
```

**Comment by bbayles** [comment]
Thanks for the writeup. I'm -0 on this one. `starfilter(lambda _, pixel: pixel is not None, grid)` and `filter(lambda val: val[1] is not None, grid)` are roughly equivalent aesthetically to me.

**Comment by Skeen** [comment]
I must respectfully completely disagree with you on that @bbayles.

I find the `starfilter` approach much more aesthetically pleasing, especially since it also serves to document the parameters.

In the provided example, the definition of `grid` may be far from where the filtering happens, and thus the context of what is contained within the `grid` iterable may not be immediately obvious. This is less of an issue with a simple `is not None` filter, but could be of great importance if the filtering step was calling a function using the arguments, say:
```python
starfilter(lambda _, pixel: check_alpha(pixel), grid)
```
versus:
```python
filter(lambda val: check_alpha(val[1]), grid)
```
In the first example, it's immediately obvious that the `alpha` property refers to translucency, while in the second line alpha could mean a lot of things, since we do not have any context.

Additionally `starfilter` might be used in a context where the function called is not a lambda, but rather an existing filter-function:
```python
starfilter(existing_filter_function, iterable)
```
versus:
```python
filter(lambda val: existing_filter_function(*val), iterable)
```
And in this case the code is simply more concise using `starfilter`.

**Comment by Skeen** [comment]
I also image that `starfilter` can be very useful for implementing dictionary filters:
```python3
>>> dictionary = {'a': 1, 'b': 2, 'c': 1}
>>> dict(starfilter(lambda key, value: value == 1, dictionary.items()))
{'a': 1, 'c': 1}
```

**Comment by jaraco** [comment]
I'd also like to see `starfilter` for the same reasons that `starmap` exists. And obviously the owner of [iteration utilities feels the same](https://iteration-utilities.readthedocs.io/en/latest/generated/starfilter.html).

In my use-case, I had [this code](https://github.com/pypa/distutils/blob/131eff757c51fa8781404a8f1d46c358804a0ce7/distutils/dep_util.py#L40-L43), where a public function (`newer`) already exists to compare two items and now I want to apply that as a filter against a sequence of such pairs. [starfilter](https://github.com/pypa/distutils/commit/4d82dc4a053c7e8b7a5720b5a4db7da2ca2ea912) is perfect for that purpose.

In my opinion, it's preferable to separate the two concerns and let the user build on a reusable abstraction rather than require every user downstream to inline the concern of splatting the items to arguments.

But now that I think about it, perhaps the best place for abstraction is not across each iteration function (i.e. `map`/`filter`/...) but across functions themselves. Perhaps the best solution would be to have a generic `splat(func)` that wraps `func` to accept a single parameter and splat it out to arguments to `func`. In that way, one could write `filter(splat(pred), iterable)` or `map(splat(func), iterable)` to get the same effect as `starfilter`/`starmap`. This approach would have the added benefit of allowing for another function `double_splat` or `splatsplat` or similar to perform a similar operation for kwargs, such as suggested by Skeen.

**Comment by jaraco** [comment]
> perhaps the best place for abstraction is... across the functions themselves.

In [jaraco.functools 4.0](https://jaracofunctools.readthedocs.io/en/latest/history.html#v4-0-0), I've added a [splat function](https://jaracofunctools.readthedocs.io/en/latest/index.html#jaraco.functools.splat) that serves the needs of `starmap` and `starfilter` and `starstarfilter`:

```python
 ~ @ pip-run 'jaraco.functools>=4'
Python 3.12.0 (main, Oct  5 2023, 15:44:07) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> grid = [('coord1', 256), ('coord2', None)]
>>> from jaraco.functools import splat
>>> res = filter(splat(lambda _, pixel: pixel is not None), grid)
>>> print(list(res))
[('coord1', 256)]
>>> iterable = [{'a': 1, 'b': 2}, {'a': None, 'b': 4}, {'a': 5, 'b': 6}]
>>> list(filter(splat(lambda a, b: a is not None), iterable))
[{'a': 1, 'b': 2}, {'a': 5, 'b': 6}]
```
For me, this completely satisfies my desire for starfilter.
