### ISSUE TITLE
Have matmul() rely on private versions of batched() and transpose()

### ISSUE THREAD

**Issue by rhettinger** [more-itertools/more-itertools#733]
The more-itertools version of `batched()` will start emitting deprecation warnings as soon as Python 3.12 goes final, so the `matmul()` recipe should use its own private version instead.  For 3.12, it can use the real `itertools.batched()` which is much faster, has improved error checking, and has fixed the API to yield tuples instead of lists (like `enumerate`, `zip`, etc.).

Since the `matmul()` recipe is somewhat new, it is not too late to have it return `Iterator[tuple]` instead of `Iterator[list]`.  Better to that switch now than to wait for 3.9 to hit end-of-life by which time `matmul()` will already have an established user base.  If lists are returned, it is almost certain that people will rely on it and mutate their matrices in place.

Also, in Python versions where `zip()` supports `strict`, the `matmul()` recipe should use it.   Making sure the matrix dimensions are compatible is something we really want — silently dropping data is hazardous.

Here is some suggested code:

```
try:

    from itertools import batched as _batched

except ImportError:
    
    def _batched(iterable, n):
        if n < 1:
            raise ValueError('n must be at least one')
        it = iter(iterable)
        while True:
            batch = tuple(islice(it, n))
            if not batch:
                break
            yield batch


try:

    zip(strict=True)

except TypeError:

    _transpose = transpose

else:

    def _transpose(it):
        "Swap the rows and columns of the input."
        # transpose([(1, 2, 3), (11, 22, 33)]) --> (1, 11) (2, 22) (3, 33)
        return zip(*it, strict=True)


def matmul(m1, m2):
    """Multiply two matrices.
    >>> list(matmul([(7, 5), (3, 5)], [(2, 5), (7, 9)]))
    [(49, 80), (41, 60)]

    The caller should ensure that the dimensions of the input
    matrices are compatible with each other.  In Python 3.9
    and later, will raise ValueError for incompatible sizes.
    """
    n = len(m2[0])
    return _batched(starmap(_sumprod, product(m1, _transpose(m2))), n)
```

**Comment by bbayles** [comment]
Thanks! I'll implement this as you suggest.

**Comment by bbayles** [comment]
In PR #734, I'm making some associated changes...

The `DeprecationWarning`s have always come back to annoy me; I've changed course and made `more_itertools.recipes.batched` an alias for `itertools.batched` for newer versions of Python. I did something similar for `pairwise` and evidently forgot about it.

I've also made `transpose` use `zip` with `strict=True` wherever possible.

`matmul` thus now issues tuples instead of lists.

These changes seem like good ones to make with a major version upgrade, which I was going to do anyway when deprecating Python 3.7.

Thanks again!
