### ISSUE TITLE
Adding `min_size` and `max_size` parameters to `powerset`.

### ISSUE THREAD

**Issue by thierry-moisan-servicenow** [more-itertools/more-itertools#775]
I was wondering if it would be possible to add the parameters `min_size` and `max_size` to the `powerset` itertools to limit the size of the returned combinations.

**Comment by bbayles** [comment]
Thanks for the suggestion. What sort of problem does this solve? Is there a StackOverflow thread, or example of code that works around this issue we can examine on GitHub?

**Comment by thierry-moisan-servicenow** [comment]
In one case I was looking for all set in the `powerset` except the empty one. In another case I wanted all powerset up to a given size which was smaller than the size of passed iterable.

I don't have any StackOverflow thread. However looking a the `powerset` source, it would be simple to pass to values to the `range`. Altough I understand there are few edge cases to cover.

**Comment by bbayles** [comment]
I think I'm going to decline this change request. `powerset` is a two-line function, so I think anybody who might want to use this extra functionality would not really save much by importing it instead of defining it themselves. In general I try to keep the `recipes` the same as they are in the `itertools` docs, though there are a few exceptions.

**Comment by thierry-moisan-servicenow** [comment]
That makes sense. Thanks for the quick response!
