### ISSUE TITLE
JoinMapping: A class to join mappings with equal keys into one mapping

### ISSUE THREAD

**Issue by NeilGirdhar** [more-itertools/more-itertools#839]
### Background
I find that I sometimes need to iterate over multiple mappings having identical keys.  Thus, I do something like:
```python
def f(a: Mapping[Key, Value], b: Mapping[Key, Value], c: Mapping[Key, Value]) -> Any:
    for key, a_value in a.items():
        b_balue = b[key]
        c_balue = c[key]
        ...
```
This has one downside of not verifying that `a`, `b`, and `c` have identical keys.  The `strict` flag was added to `zip` to do a similar verification because it's extremely useful.  This also has the downside of being slightly convoluted (iteration happens on `a` instead of on all of them, and the key lookups happen on only `b` and `c`.

### Proposal
Add an itertool class that reflects the parallel structure and verifies equivalence of keys:
```python
from collections.abc import Iterator, Mapping
from typing import TypeVar, override


K = TypeVar('K')
V = TypeVar('V')


class JoinMapping(Mapping[K, tuple[V, ...]]):
    def __init__(self, x: Mapping[K, V], /, *args: Mapping[K, V]):
        super().__init__()
        self.mappings = x, *args
        n = len(x)
        s = set(x)
        for y in args:
            if len(y) != n:
                raise ValueError
            if set(y) != s:
                raise ValueError

    @override
    def __getitem__(self, key: K) -> tuple[V, ...]:
        return tuple(mapping[key] for mapping in self.mappings)

    @override
    def __iter__(self) -> Iterator[K]:
        return iter(self.mappings[0])

    @override
    def __len__(self) -> int:
        return len(self.mappings[0])
```
This checks for equal lengths, iterates over one mapping, while indexing the other mappings.  I initially thought of proposing this for Python, but I think if this were to be added, it would belong in more-itertools first.

This is a bit like `ChainMap` in the sense that it combines mappings, but instead of delegation of values, it creates tuples of keys.

### Examples
```python
JoinMappings(a, b, c)[x]  #  equivalent to (a[x], b[x], c[x])
JoinMappings(a, b, c).items()  # equivalent to ((k, (a[k], b[k], c[k])) for k in a)
JoinMappings(a, b, c).values()  # equivalent to ((a[k], b[k], c[k]) for k in a)
# etc.
```

**Comment by m9810223** [comment]
How about [collections.ChainMap](https://docs.python.org/3/library/collections.html#collections.ChainMap)？

**Comment by rhettinger** [comment]
+1 on the core idea. The concept of an equijoin is fundamental. This would make a nice building block although I'm not sure how often the need would arise in practice.

Misc ideas and food for thought:

* I'm not sure I would have thought of this as a lazily constructed view of the underlying mappings. Is there any downside to running this immediately and producing an actual dict of tuples?

```
>>> JoinMapping(salary, dept, service))
{'e1': (12, 'eng', 5), 'e2': (23, 'sales', 8), 'e3': (34, 'eng', 2)}
```

* Consider allowing a dataclass or namedtuple to be passed in:

```
>>> Employee = namedtuple('Employee', ('salary', 'dept', 'service'))
>>> JoinMapping(salary, dept, service, cast=Employee)
{'e1': Employee(salary=12, dept='eng', service=5),
 'e2': Employee(salary=23, dept='sales', service=8),
 'e3': Employee(salary=34, dept='eng', service=2)}
```

* Given field names, it may be better to output dictionaries instead of tuples.  A dict of dicts is a common and familiar pattern:

```
>>> JoinMapping(salary, dept, service, field_names = ('salary', 'dept', 'service'))
{'e1': {'salary': 12, 'dept': 'eng', 'service': 5},
 'e2': {'salary': 23, 'dept': 'sales', 'service': 8},
 'e3': {'salary': 34, 'dept': 'eng', 'service': 2}}
```

**Comment by rhettinger** [comment]
Thanks for the suggestion.  I'll mark this as `pending` since you've submitted it to `more-itertools`.  

FWIW As presented above this would end up in the `collections` module which houses mapping variants rather than `itertools` which houses functions that produce iterators.

**Comment by bbayles** [comment]
> I'm not sure I would have thought of this as a lazily constructed view of the underlying mappings. Is there any downside to running this immediately and producing an actual dict of tuples?

I think running immediately makes more sense, and is similar to what `map_reduce` does.

> Given field names, it may be better to output dictionaries instead of tuples. A dict of dicts is a common and familiar pattern:

Here's something that feels nice to use - there's need to specify the field names separately from the mappings:

```python3
In [15]: def join_mapping(**field_maps):
    ...:     ret = defaultdict(dict)
    ...:     for field_name, mapping in field_maps.items():
    ...:         for key, value in mapping.items():
    ...:             ret[key][field_name] = value
    ...:     return ret
    ...:

In [16]: join_mapping(salary=salary, dept=dept, service=service)
Out[16]:
defaultdict(dict,
            {'e1': {'salary': 12, 'dept': 'eng', 'service': 5},
             'e2': {'salary': 23, 'dept': 'sales', 'service': 9},
             'e3': {'salary': 34, 'dept': 'eng', 'service': 2}})
```

(validation excluded)

One issue is that this restricts the field names to identifiers, so maybe it would make more sense to pass in a mapping of mappings.

**Comment by bbayles** [comment]
Here's an implementation with `strict` validation: https://github.com/more-itertools/more-itertools/issues/839

**Comment by rhettinger** [comment]
Here a link to the trial implementation: https://github.com/more-itertools/more-itertools/pull/841

After trying it out, I have some thoughts and suggestions.  From a user point of view, the API feels a little awkward due to 1) needing to form *field_to_map* prior to the join operation and 2) returning a *defaultdict* when a dict would be cleaner (especially when used with *pprint*).

ISTM the *field_to_map* dictionary input is less desirable than a more elegant keyword argument input, but it was needed to overcome two limitations of keyword arguments: 1) keyword arguments are restricted to non-keyword identifiers, and 2) avoiding conflict with the `strict` option which is keyword-only.

We don't really care about the first restriction.  That is what drove the `rename` option for `collections.namedtuple()`, but in practice, no one uses that option. FWIW, SQL has similar restrictions where reserved words and invalid identifiers cannot be used as field names. That hasn't proven to be a problem in practice.

Also, I don't think we really need or want a `strict` option.  One reason is that if a `ValueError` does get raised there is no easy way to recover.  Another is that this check could easily be implemented by a user after the join — it really is an orthogonal step. Contrast that with `zip()` where a user could not implement a *strict* option themselves.  If a user does implement their own check, they can also choose what to do about it, perhaps adding a default value or logging the result. Special handling that allows the join to run to completion is something that we can't automate away.  That is best left to the user as a post processing step.

Side note: MS Excel's pivot operation does not have a *strict* option.  Instead, it just sets counts and sums to zero, or leaves the grid entry blank when fully expanded.

Rather than returning a *defaultdict*, it is simpler for the user if the join takes care of casting the result to a regular dict.  Thanks to optimizations in the dict implementation, this is very cheap (the new dict is presized exactly, the stored hash values are reused, the are no checks for duplicate keys, the slowest part is just increffing all the keys and values).

**Comment by bbayles** [comment]
Thanks for the comments. Your point about the contrast between the utility of `strict` between this and `zip` is very helpful - I originally used the `field_to_map` so as not to interfere with the `strict` parameter.

**Comment by NeilGirdhar** [comment]
> Is this still in-line with your original vision? If not, please say so. I don't want my casual suggestions to derail where you wanted to go with this.

I think your dictionary-returning approach is more elegant than my tuple approach :smile:.

I'd like to get your thoughts on a add a concrete, real-world at how this might be used.  I have [some code](https://github.com/NeilGirdhar/efax/blob/3a7ba4545b2ea4c851d53995a64837fc2e9b7121/efax/_src/transform/joint.py#L71) in mind that motivated this request.  Currently, I have:
```python
    def carrier_measure(self, x: dict[str, Any]) -> JaxRealArray:
        return reduce(jnp.add,
                      (value.carrier_measure(x[name])
                       for name, value in self.sub_distributions_objects.items()))
```
With your incantantation of `join_mappings`, I could do
```python
    def carrier_measure(self, x: dict[str, Any]) -> JaxRealArray:
        joined = join_mappings(sub_distribution=self.sub_distributions_objects.items(), sub_x=x)
        return reduce(jnp.add,
                      (d['sub_distribution'].carrier_measure(d['sub_x']) for name, d in joined.items()))
```
which has the benefit of exposing the parallel structure to the reader rather than cloaking it.  What do you think?

> Another is that this check could easily be implemented by a user after the join

Good point.  And because of the way you defined `join_mappings`, the above code raises if the mappings don't match (although I should really check that `set(self.sub_distribution_objects) == set(x)` to produce a nicer error).

**Comment by rhettinger** [comment]
In your examples, *join_mappings()* seems to be a good fit. Real world use cases really help to validate an API.

**Comment by bbayles** [comment]
This will be in the next release. Thanks!

**Comment by NeilGirdhar** [comment]
Awesome, thanks both!
