### ISSUE TITLE
Proposal for cycled_sliding_window

### ISSUE THREAD

**Issue by miekmesserschmidt** [more-itertools/more-itertools#840]
### Description

This issue proposes add `cycled_sliding_window`. It is similar to `sliding_window` but the window slides past the end of the iterable (which is cycled), stopping when the last element of the iterable appears as the 0th element of the window.

Unless I am mistaken, this is tedious to achieve with current `itertools` and `more-itertools`. One could do a `sliding_window` over a `cycle`, but then it is not clear when to stop iteration. The user is required to do some analysis of the input iterator to stop iteration at the right position  (tee'ing and zipping as in the proposed implementation below). 

### References

I came across needing this when implementing some of McKay's algorithms for nonisomorphic generation.  [[1]](http://users.cecs.anu.edu.au/~bdm/papers/orderly.pdf) [[2]](https://users.cecs.anu.edu.au/~bdm/papers/plantri-full.pdf). 

Specifically, one needs to identify certain substructures of a planar graph by examining sliding windows of a node's neighbours. Neighbours of a node in a planar graph can be represented as a list of nodes representing the clockwise order in which they appear around a node. In scanning for the presence of certain substructures, one needs to examine a sliding window that wraps around the end of such a list of neighbours.

### Examples

Return a sliding window of width *n* over the cycled *iterable* so that each item in the iterable appears exactly once as the 0th item in the window.

```python
>>> list(cycled_sliding_window(range(6), 4))
[(0, 1, 2, 3), (1, 2, 3, 4), (2, 3, 4, 5), (3, 4, 5, 0), (4, 5, 0, 1), (5, 0, 1, 2)]

```

If *iterable* has fewer than *n* items, the window wraps around the iterable as many times as is required:

```python
>>> list(cycled_sliding_window(range(3), 7))
[(0, 1, 2, 0, 1, 2, 0), (1, 2, 0, 1, 2, 0, 1), (2, 0, 1, 2, 0, 1, 2)]
```

### Proposed Implementation

```python
def cycled_sliding_window(iterable, n):
    """Return a sliding window of width *n* over the cycled *iterable* so that each item in the iterable appears exactly once as the 0th item in the window.

        >>> list(cycled_sliding_window(range(6), 4))
        [(0, 1, 2, 3), (1, 2, 3, 4), (2, 3, 4, 5), (3, 4, 5, 0), (4, 5, 0, 1), (5, 0, 1, 2)]

    If *iterable* has fewer than *n* items, the window wraps around the iterable as many times as is required:

        >>> list(cycled_sliding_window(range(3), 7))
        [(0, 1, 2, 0, 1, 2, 0), (1, 2, 0, 1, 2, 0, 1), (2, 0, 1, 2, 0, 1, 2)]


    See also :func:`sliding_window`.
    """
    it = iter(iterable)
    it0, it1 = itertools.tee(it)
    cycle = itertools.cycle(it1)

    window = deque(islice(cycle, n - 1), maxlen=n)
    for _, item in zip(it0, cycle):
        window.append(item)
        yield tuple(window)

```

**Comment by bbayles** [comment]
Thanks for the suggestion. I'm not inclined to bring this functionality into the library, though if you have instances of people trying to solve the same problem on Stack Overflow and GitHub, I'll reconsider.

Thanks again!

**Comment by monk-time** [comment]
A number of times in the past I felt the need for a function like this but I admit it wasn't in prod code but rather for leetcode-type exercises. Although I can see it being useful in some testing scenarios where it's important to keep the relative order of items but some check must be made starting from every position in an iterable, looping around the end. 

Nonetheless I tried to look up some examples on the net of other people needing this and found only a few:

[StackOverflow: Cyclical Sliding Window Iteration](https://stackoverflow.com/questions/30415288/cyclical-sliding-window-iteration)
The most popular question on SO that requests specifically this kind of a function.

[StackOverflow: How to loop over a circular list, while peeking ahead and behind current element?](https://stackoverflow.com/questions/12010820/how-to-loop-over-a-circular-list-while-peeking-ahead-and-behind-current-element)
The suggested function would solve this question in the following way:

```py
for prev, cur, next_ in cycled_sliding_window(iter, 3):
    ...
```

[GitHub: `ubelt`](https://github.com/Erotemic/ubelt/blob/1da8198971afd1809d940e50619491291c5a0fc8/ubelt/util_list.py#L604)
The library `ubelt` implements a `sliding_window` variant with an optional wrap flag. The first example in the docstring would be equilavent to this:

```py
print(list(cycled_sliding_window(range(1, 7), 3)))
```
