### ISSUE TITLE
Evaluate new recipe for the main itertools docs

### ISSUE THREAD

**Issue by rhettinger** [more-itertools/more-itertools#908]
I've drafted a new `lookahead/preview` recipe for the CPython itertools docs.  Since everything that goes there eventually ends up in `more-itertools`, I would like to solicit comments here.

```
from itertools import tee, islice

def take(n, iterable):
    return list(islice(iterable, n))

def lookahead(tee_iterator, n=1):
    """Preview up to n values from a tee iterator object.

        >>> it = iter('abcde')
        >>> [it] = tee(it, 1)

        >>> lookahead(it, n=3)
        ['a', 'b', 'c']
        >>> next(it)
        'a'

        >>> lookahead(it, n=3)
        ['b', 'c', 'd']
        >>> next(it)
        'b'

        >>> lookahead(it)
        ['c']
        >>> list(it)
        ['c', 'd', 'e']

    """
    return take(n, tee(tee_iterator)[1])
```

**Notes**:

1) I'm undecided on whether to call this `lookahead` or `preview`.

2) The code above has a workaround for a subtle bug in the current `itertools.tee()` implementation, so we actually do need `tee(tee_iterator)[1])` instead of `tee(tee_iterator, 1)[0])`.

3) One thing I really like about this is that the existing iterator can continue to be used.  The downside is that is recipe doesn't work at all for non-tee inputs (it consumes values from the input iterator).  This is something that tee objects can do that other iterators can't.

4) If the risk of incorrect use is too high, I might have to add a test to verify the input is a tee().

5) I'm also planning to retire the `partition()` recipe because this is a much between demonstration of `tee()` and because it is almost always the wrong way to solve that problem.

**Comment by pochmann3** [comment]
Seems awfully dependent on CPython implementation details, and not just because of that workaround. Goes against the *"Once a tee() has been created, the original iterable should not be used anywhere else"* of the `tee` doc. Is that really something you want to teach and encourage? And does it even work in other implementations like PyPy?

**Comment by rhettinger** [comment]
Aside from the bug workaround, all of the behaviors are guaranteed. And yes it works on PyPy.  From the outset, `tee()` was designed to support flattening of nested calls.  That supported a key use case:  efficient repeated forking of iterator streams.

At some point, I expect to move the "once created, not used anywhere else" guidance to intro section.  It is a pretty good first approximation to keep people from shooting themselves in the foot. And it broadly applies to any itertool or recipe that lazily consumes its input (`chain()` for example).   However, that is only a first approximation. Pretty much everything that accepts an iterator has specific and useful rules about how much of the input is consumed.  For example, `next()`, `islice()`, and `dropwhile()` could not be used in a loop without such guarantees.

I'm not sure how much to "teach and encourage" but do need to demonstrate how to fork off of an existing tee instance. From the outset, it was designed for that.

**Comment by rhettinger** [comment]
I'm going to close this and meditate on it for while.

**Comment by pochmann3** [comment]
Hmm, what/where is the guarantee? The only statement I see about using the original iterable after being tee'd is that explicit *warning* I quoted. Which seems extra important because such a warning isn't given for the other tools.

If you do want to demonstrate how to fork off of an existing tee instance, then maybe just do that? Call it `fork_tee` and leave out the `take`? Can still use `take` in the docstring example.

And given that it's `tee`-specific and is supposed to inform about `tee`, maybe don't put/hide it in the recipes but instead add it to `tee`'s documentation, mentioning the design goals you just mentioned?

That would also add some *good* news to its doc :-). Currently that's just three paragraphs all about *dangers* :-(

**Comment by bbayles** [comment]
For [spy](https://github.com/more-itertools/more-itertools/blob/4998a257373f36e91edef7324572ed8df10f39d1/more_itertools/more.py#L1084-L1124), we `take` from the iterable, then return a tuple with those items and a `chain` object of those items plus what's left of the original iterable.

I like this because it's a nice demonstration of how to use `chain`, but it would be nice to have some examples of advanced uses of `tee`.
